from __future__ import annotations

import csv
import io
import json
import os
from contextlib import contextmanager
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any, Iterator

import psycopg
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

ENV_PATH = Path(__file__).resolve().parent.parent / ".env"


def _load_env_file() -> None:
    """Lee backend/.env sin depender de python-dotenv. Las variables ya
    presentes en el entorno ganan, para que Dokploy pueda inyectar las suyas."""
    if not ENV_PATH.exists():
        return
    for raw in ENV_PATH.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


def database_url() -> str:
    _load_env_file()
    url = os.getenv("DATABASE_URL", "").strip()
    if not url:
        raise RuntimeError(
            "Falta DATABASE_URL. Definela en el entorno o en backend/.env, p.ej.\n"
            "  DATABASE_URL=postgresql://usuario:clave@127.0.0.1:5432/coachfit"
        )
    return url


_pool: ConnectionPool | None = None


def _get_pool() -> ConnectionPool:
    global _pool
    if _pool is None:
        pool = ConnectionPool(
            database_url(),
            min_size=1,
            max_size=10,
            kwargs={"row_factory": dict_row},
            open=False,
        )
        pool.open(wait=True, timeout=30)
        _pool = pool
    return _pool


def close_pool() -> None:
    global _pool
    if _pool is not None:
        _pool.close()
        _pool = None


@contextmanager
def get_db() -> Iterator[psycopg.Connection]:
    """Una conexion del pool por operacion. El context manager de psycopg hace
    commit al salir sin error y rollback si hay excepcion, igual que la version
    sqlite que esto reemplaza."""
    with _get_pool().connection() as conn:
        yield conn


# Postgres siempre aplica las claves foraneas, asi que no hay equivalente del
# PRAGMA foreign_keys que usaba la version sqlite.
SCHEMA = """
CREATE TABLE IF NOT EXISTS body_metrics (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date TEXT NOT NULL,
  measured_at TEXT,
  weight_kg DOUBLE PRECISION,
  bmi DOUBLE PRECISION,
  body_fat_pct DOUBLE PRECISION,
  fat_mass_kg DOUBLE PRECISION,
  muscle_pct DOUBLE PRECISION,
  muscle_mass_kg DOUBLE PRECISION,
  skeletal_muscle_pct DOUBLE PRECISION,
  skeletal_muscle_kg DOUBLE PRECISION,
  bone_pct DOUBLE PRECISION,
  bone_mass_kg DOUBLE PRECISION,
  protein_pct DOUBLE PRECISION,
  protein_mass_kg DOUBLE PRECISION,
  water_pct DOUBLE PRECISION,
  water_mass_kg DOUBLE PRECISION,
  lean_body_mass_kg DOUBLE PRECISION,
  subcutaneous_fat_pct DOUBLE PRECISION,
  visceral_fat DOUBLE PRECISION,
  bmr_kcal DOUBLE PRECISION,
  metabolic_age DOUBLE PRECISION,
  whr DOUBLE PRECISION,
  optimal_weight_kg DOUBLE PRECISION,
  weight_level TEXT,
  body_type TEXT,
  notes TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS body_metric_photos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  body_metric_id INTEGER NOT NULL REFERENCES body_metrics(id) ON DELETE CASCADE,
  object_key TEXT NOT NULL UNIQUE,
  original_name TEXT,
  content_type TEXT NOT NULL,
  size_bytes INTEGER NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS body_metric_photos_by_metric
  ON body_metric_photos (body_metric_id, sort_order, id);

-- Foto de perfil del único usuario. Independiente de las fotos de cada
-- medición corporal: un solo avatar, reemplazable.
CREATE TABLE IF NOT EXISTS user_profile (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  photo_object_key TEXT,
  photo_content_type TEXT,
  photo_original_name TEXT,
  photo_size_bytes INTEGER,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS runs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date TEXT NOT NULL,
  distance_km DOUBLE PRECISION NOT NULL,
  duration_min DOUBLE PRECISION,
  pace_min_per_km DOUBLE PRECISION,
  rpe INTEGER,
  notes TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date TEXT NOT NULL UNIQUE,
  focus TEXT,
  completed INTEGER NOT NULL DEFAULT 0,
  session_rpe INTEGER,
  notes TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS session_sets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  exercise_id TEXT NOT NULL,
  set_index INTEGER NOT NULL,
  reps INTEGER,
  weight_kg DOUBLE PRECISION,
  rpe INTEGER,
  done INTEGER NOT NULL DEFAULT 1,
  notes TEXT
);

CREATE TABLE IF NOT EXISTS week_plan (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  payload TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS coach_notes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TEXT NOT NULL,
  week_start TEXT NOT NULL,
  prompt_summary TEXT,
  advice TEXT NOT NULL,
  source TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS user_equipment (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  equipment_type TEXT NOT NULL,
  weight_kg DOUBLE PRECISION,
  quantity INTEGER DEFAULT 1,
  created_at TEXT NOT NULL
);

-- Multiples planes guardados, uno activo. Sustituye al singleton week_plan,
-- que queda como legado de solo lectura: sin sistema de migraciones lo unico
-- seguro es crear tablas nuevas, nunca alterar las que ya tienen datos.
CREATE TABLE IF NOT EXISTS plans (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  payload TEXT NOT NULL,
  is_active INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- Nombres unicos sin distinguir mayusculas: "Piernas" y "piernas" son el mismo
-- plan para el usuario.
CREATE UNIQUE INDEX IF NOT EXISTS plans_name_unique ON plans (lower(name));

-- Como maximo un plan activo, garantizado por la base y no solo por la app. El
-- indice parcial obliga a apagar el activo antes de encender el nuevo.
CREATE UNIQUE INDEX IF NOT EXISTS plans_single_active
  ON plans (is_active) WHERE is_active = 1;

-- Espacios de entrenamiento («gimnasios virtuales»): casa, gimnasio comercial,
-- parque, hotel, oficina. El equipo deja de ser global y pasa a colgar de uno de
-- estos. user_equipment queda intacta como legado de solo lectura, igual que
-- week_plan: sin sistema de migraciones lo unico seguro es crear tablas nuevas.
CREATE TABLE IF NOT EXISTS gyms (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  -- hogar|comercial|outdoor|temporal|oficina. Deliberadamente SIN CHECK: una
  -- restriccion de enumerado sobre una tabla ya creada no se puede ampliar sin
  -- ALTER, y esta lista va a crecer. Se valida en gyms.normalize_kind().
  kind TEXT NOT NULL DEFAULT 'hogar',
  icon TEXT,
  color TEXT,
  notes TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- Nombres unicos sin distinguir mayusculas, igual que plans_name_unique. Ademas
-- es lo que hace segura la siembra concurrente en bootstrap_gyms().
CREATE UNIQUE INDEX IF NOT EXISTS gyms_name_unique ON gyms (lower(name));

-- Inventario por espacio. Mismas columnas que user_equipment mas gym_id, para
-- que el backfill sea una copia columna a columna y el tipo del frontend no
-- cambie de forma. Aqui quantity SI es NOT NULL: la tabla vieja lo dejo
-- nullable y el copiado lo arregla con COALESCE.
CREATE TABLE IF NOT EXISTS gym_equipment (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gym_id INTEGER NOT NULL REFERENCES gyms(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  equipment_type TEXT NOT NULL,
  weight_kg DOUBLE PRECISION,
  quantity INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL
);

-- Cubre el filtro por espacio y el ORDER BY del listado a la vez.
CREATE INDEX IF NOT EXISTS gym_equipment_by_gym
  ON gym_equipment (gym_id, equipment_type, name);

-- Curacion de la biblioteca, ESPARCIDA a proposito: solo se guardan las marcas
-- explicitas («favorito» y «oculto»). «disponible» es el estado por defecto de
-- todo lo que el inventario permite y NUNCA ocupa una fila — con 1324
-- ejercicios y varios espacios seria repetir miles de veces el valor por
-- defecto. Ese invariante lo sostiene db.set_exercise_pref(), no la base.
CREATE TABLE IF NOT EXISTS gym_exercise_prefs (
  gym_id INTEGER NOT NULL REFERENCES gyms(id) ON DELETE CASCADE,
  -- Sin FK: el catalogo es un JSON, no una tabla. Misma decision que
  -- session_sets.exercise_id.
  exercise_id TEXT NOT NULL,
  state TEXT NOT NULL,
  created_at TEXT NOT NULL,
  -- Clave natural: nada referencia una marca por id propio. Da gratis el
  -- barrido por gym_id y el destino del upsert.
  PRIMARY KEY (gym_id, exercise_id)
);
"""

BODY_METRIC_COLUMN_DEFS: tuple[tuple[str, str], ...] = (
    ("measured_at", "TEXT"),
    ("bmi", "DOUBLE PRECISION"),
    ("fat_mass_kg", "DOUBLE PRECISION"),
    ("muscle_pct", "DOUBLE PRECISION"),
    ("muscle_mass_kg", "DOUBLE PRECISION"),
    ("skeletal_muscle_pct", "DOUBLE PRECISION"),
    ("skeletal_muscle_kg", "DOUBLE PRECISION"),
    ("bone_pct", "DOUBLE PRECISION"),
    ("bone_mass_kg", "DOUBLE PRECISION"),
    ("protein_pct", "DOUBLE PRECISION"),
    ("protein_mass_kg", "DOUBLE PRECISION"),
    ("water_pct", "DOUBLE PRECISION"),
    ("water_mass_kg", "DOUBLE PRECISION"),
    ("lean_body_mass_kg", "DOUBLE PRECISION"),
    ("subcutaneous_fat_pct", "DOUBLE PRECISION"),
    ("visceral_fat", "DOUBLE PRECISION"),
    ("bmr_kcal", "DOUBLE PRECISION"),
    ("metabolic_age", "DOUBLE PRECISION"),
    ("whr", "DOUBLE PRECISION"),
    ("optimal_weight_kg", "DOUBLE PRECISION"),
    ("weight_level", "TEXT"),
    ("body_type", "TEXT"),
)


def init_db() -> None:
    with get_db() as conn:
        conn.execute(SCHEMA)
        for name, ddl in BODY_METRIC_COLUMN_DEFS:
            conn.execute(f"ALTER TABLE body_metrics ADD COLUMN IF NOT EXISTS {name} {ddl}")


def now_iso() -> str:
    return datetime.now().isoformat(timespec="seconds")


def upsert_session(
    day: str,
    *,
    focus: str | None = None,
    completed: bool | None = None,
    session_rpe: int | None = None,
    notes: str | None = None,
) -> dict[str, Any]:
    with get_db() as conn:
        row = conn.execute("SELECT * FROM sessions WHERE date = %s", (day,)).fetchone()
        ts = now_iso()
        if row is None:
            conn.execute(
                """
                INSERT INTO sessions (date, focus, completed, session_rpe, notes, created_at, updated_at)
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                """,
                (
                    day,
                    focus,
                    1 if completed else 0,
                    session_rpe,
                    notes,
                    ts,
                    ts,
                ),
            )
        else:
            # Los casts explicitos evitan que Postgres se quede sin tipo cuando el
            # parametro llega NULL dentro de un COALESCE.
            conn.execute(
                """
                UPDATE sessions
                SET focus = COALESCE(%s::text, focus),
                    completed = COALESCE(%s::integer, completed),
                    session_rpe = COALESCE(%s::integer, session_rpe),
                    notes = COALESCE(%s::text, notes),
                    updated_at = %s
                WHERE date = %s
                """,
                (
                    focus,
                    None if completed is None else (1 if completed else 0),
                    session_rpe,
                    notes,
                    ts,
                    day,
                ),
            )
        return dict(conn.execute("SELECT * FROM sessions WHERE date = %s", (day,)).fetchone())


def replace_session_sets(session_id: int, sets: list[dict[str, Any]]) -> list[dict[str, Any]]:
    with get_db() as conn:
        conn.execute("DELETE FROM session_sets WHERE session_id = %s", (session_id,))
        for s in sets:
            conn.execute(
                """
                INSERT INTO session_sets
                (session_id, exercise_id, set_index, reps, weight_kg, rpe, done, notes)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                """,
                (
                    session_id,
                    s["exercise_id"],
                    s["set_index"],
                    s.get("reps"),
                    s.get("weight_kg"),
                    s.get("rpe"),
                    1 if s.get("done", True) else 0,
                    s.get("notes"),
                ),
            )
        rows = conn.execute(
            "SELECT * FROM session_sets WHERE session_id = %s ORDER BY exercise_id, set_index",
            (session_id,),
        ).fetchall()
        return [dict(r) for r in rows]


def get_session(day: str) -> dict[str, Any] | None:
    with get_db() as conn:
        row = conn.execute("SELECT * FROM sessions WHERE date = %s", (day,)).fetchone()
        if not row:
            return None
        sets = conn.execute(
            "SELECT * FROM session_sets WHERE session_id = %s ORDER BY exercise_id, set_index",
            (row["id"],),
        ).fetchall()
        out = dict(row)
        out["completed"] = bool(out["completed"])
        out["sets"] = [dict(s) | {"done": bool(s["done"])} for s in sets]
        return out


def list_sessions(start: str, end: str) -> list[dict[str, Any]]:
    with get_db() as conn:
        # SUM y AVG devuelven numeric en Postgres; sin el cast a double precision
        # llegarian como Decimal y romperian la aritmetica de compute_weekly_load.
        rows = conn.execute(
            """
            SELECT s.*,
              CAST(COALESCE(SUM(ss.reps * COALESCE(ss.weight_kg, 0)), 0) AS DOUBLE PRECISION) AS volume_kg,
              COUNT(ss.id) AS set_count,
              CAST(AVG(ss.rpe) AS DOUBLE PRECISION) AS avg_set_rpe
            FROM sessions s
            LEFT JOIN session_sets ss ON ss.session_id = s.id AND ss.done = 1
            WHERE s.date BETWEEN %s AND %s
            GROUP BY s.id
            ORDER BY s.date
            """,
            (start, end),
        ).fetchall()
        out = []
        for r in rows:
            d = dict(r)
            d["completed"] = bool(d["completed"])
            out.append(d)
        return out


BODY_METRIC_INSERT_FIELDS = (
    "date",
    "measured_at",
    "weight_kg",
    "bmi",
    "body_fat_pct",
    "fat_mass_kg",
    "muscle_pct",
    "muscle_mass_kg",
    "skeletal_muscle_pct",
    "skeletal_muscle_kg",
    "bone_pct",
    "bone_mass_kg",
    "protein_pct",
    "protein_mass_kg",
    "water_pct",
    "water_mass_kg",
    "lean_body_mass_kg",
    "subcutaneous_fat_pct",
    "visceral_fat",
    "bmr_kcal",
    "metabolic_age",
    "whr",
    "optimal_weight_kg",
    "weight_level",
    "body_type",
    "notes",
)

RENPHO_FIELD_MAP = {
    "Fecha": "date",
    "Hora": "measured_at",
    "Peso(kg)": "weight_kg",
    "IMC": "bmi",
    "Porcentaje de grasa corporal(%)": "body_fat_pct",
    "Masa grasa corporal(kg)": "fat_mass_kg",
    "Porcentaje de músculo(%)": "muscle_pct",
    "Masa muscular(kg)": "muscle_mass_kg",
    "Porcentaje de músculo esquelético(%)": "skeletal_muscle_pct",
    "Masa muscular esquelética(kg)": "skeletal_muscle_kg",
    "Porcentaje óseo(%)": "bone_pct",
    "Masa ósea(kg)": "bone_mass_kg",
    "Porcentaje de proteína(%)": "protein_pct",
    "Masa proteica(kg)": "protein_mass_kg",
    "Porcentaje de agua corporal(%)": "water_pct",
    "Masa de agua corporal(kg)": "water_mass_kg",
    "Peso corporal sin grasa(kg)": "lean_body_mass_kg",
    "Grasa subcutánea(%)": "subcutaneous_fat_pct",
    "Grasa visceral": "visceral_fat",
    "Tasa Metabólica Basal(kcal)": "bmr_kcal",
    "Edad metabólica": "metabolic_age",
    "WHR (Proporción cintura-cadera)": "whr",
    "Peso óptimo(kg)": "optimal_weight_kg",
    "Nivel de peso": "weight_level",
    "Tipo de cuerpo": "body_type",
}

BODY_METRIC_TEXT_FIELDS = {"date", "measured_at", "weight_level", "body_type", "notes"}


def _parse_float(raw: Any) -> float | None:
    if raw is None:
        return None
    value = str(raw).strip().replace(",", ".")
    if not value:
        return None
    try:
        return float(value)
    except ValueError:
        return None


def _parse_renpho_date(raw: str) -> str:
    return datetime.strptime(raw.strip(), "%m/%d/%y").date().isoformat()


def _parse_renpho_time(raw: str | None) -> str | None:
    if not raw:
        return None
    value = raw.strip().lower().replace("\u202f", " ").replace("\xa0", " ")
    value = value.replace("a.m.", "AM").replace("p.m.", "PM")
    value = value.replace("a. m.", "AM").replace("p. m.", "PM")
    try:
        return datetime.strptime(value, "%I:%M:%S %p").time().isoformat()
    except ValueError:
        return raw.strip()


def _body_metric_payload(
    day: str,
    weight_kg: float | None = None,
    body_fat_pct: float | None = None,
    notes: str | None = None,
    **extra: Any,
) -> dict[str, Any]:
    payload = {field: extra.get(field) for field in BODY_METRIC_INSERT_FIELDS}
    payload["date"] = day
    payload["weight_kg"] = weight_kg
    payload["body_fat_pct"] = body_fat_pct
    payload["notes"] = notes
    return payload


def _insert_body_metric_in_conn(conn: psycopg.Connection, payload: dict[str, Any]) -> dict[str, Any]:
    fields = BODY_METRIC_INSERT_FIELDS
    columns = ", ".join(fields)
    placeholders = ", ".join(["%s"] * len(fields))
    row = conn.execute(
        f"""
        INSERT INTO body_metrics ({columns}, created_at)
        VALUES ({placeholders}, %s)
        RETURNING *
        """,
        tuple(payload.get(field) for field in fields) + (now_iso(),),
    ).fetchone()
    return dict(row)


def _upsert_imported_body_metric_in_conn(
    conn: psycopg.Connection, payload: dict[str, Any]
) -> dict[str, Any]:
    row = conn.execute(
        """
        SELECT id FROM body_metrics
        WHERE date = %s AND (measured_at = %s::text OR measured_at IS NULL)
        ORDER BY measured_at DESC NULLS LAST, id DESC
        LIMIT 1
        """,
        (payload["date"], payload.get("measured_at")),
    ).fetchone()
    if row is None:
        return _insert_body_metric_in_conn(conn, payload)

    fields = tuple(field for field in BODY_METRIC_INSERT_FIELDS if field != "date")
    assignments = ", ".join(f"{field} = %s" for field in fields)
    updated = conn.execute(
        f"UPDATE body_metrics SET {assignments} WHERE id = %s RETURNING *",
        tuple(payload.get(field) for field in fields) + (row["id"],),
    ).fetchone()
    return dict(updated)


def add_body_metric(
    day: str,
    weight_kg: float | None,
    body_fat_pct: float | None = None,
    notes: str | None = None,
    **extra: Any,
) -> dict[str, Any]:
    with get_db() as conn:
        return _insert_body_metric_in_conn(
            conn, _body_metric_payload(day, weight_kg, body_fat_pct, notes, **extra)
        )


def _photo_payload(row: dict[str, Any]) -> dict[str, Any]:
    # `v` cambia al reemplazar el object_key; evita imagen vieja en cache del browser.
    object_key = row.get("object_key") or ""
    version = object_key.rsplit("/", 1)[-1][:16] or str(row["id"])
    return {
        **row,
        "url": f"/api/metrics/body/photos/{row['id']}?v={version}",
    }


def _attach_body_metric_photos(conn: psycopg.Connection, metrics: list[dict[str, Any]]) -> None:
    for metric in metrics:
        metric["photos"] = []
    ids = [m["id"] for m in metrics]
    if not ids:
        return
    rows = conn.execute(
        """
        SELECT *
        FROM body_metric_photos
        WHERE body_metric_id = ANY(%s::int[])
        ORDER BY body_metric_id, sort_order, id
        """,
        (ids,),
    ).fetchall()
    by_metric = {metric_id: [] for metric_id in ids}
    for row in rows:
        photo = _photo_payload(dict(row))
        by_metric.setdefault(photo["body_metric_id"], []).append(photo)
    for metric in metrics:
        metric["photos"] = by_metric.get(metric["id"], [])


def add_body_metric_photo(
    body_metric_id: int,
    object_key: str,
    original_name: str | None,
    content_type: str,
    size_bytes: int,
    sort_order: int = 0,
) -> dict[str, Any]:
    with get_db() as conn:
        row = conn.execute(
            """
            INSERT INTO body_metric_photos (
              body_metric_id, object_key, original_name, content_type, size_bytes,
              sort_order, created_at
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            RETURNING *
            """,
            (
                body_metric_id,
                object_key,
                original_name,
                content_type,
                size_bytes,
                sort_order,
                now_iso(),
            ),
        ).fetchone()
        return _photo_payload(dict(row))


def get_body_metric_photo(photo_id: int) -> dict[str, Any] | None:
    with get_db() as conn:
        row = conn.execute(
            "SELECT * FROM body_metric_photos WHERE id = %s",
            (photo_id,),
        ).fetchone()
        return _photo_payload(dict(row)) if row else None


def get_body_metric(metric_id: int) -> dict[str, Any] | None:
    with get_db() as conn:
        row = conn.execute(
            "SELECT * FROM body_metrics WHERE id = %s",
            (metric_id,),
        ).fetchone()
        if not row:
            return None
        metric = dict(row)
        _attach_body_metric_photos(conn, [metric])
        return metric


def body_metric_photo_count(metric_id: int) -> int:
    with get_db() as conn:
        row = conn.execute(
            "SELECT COUNT(*) AS n FROM body_metric_photos WHERE body_metric_id = %s",
            (metric_id,),
        ).fetchone()
        return int(row["n"] if row else 0)


def next_body_metric_photo_sort(metric_id: int) -> int:
    with get_db() as conn:
        row = conn.execute(
            """
            SELECT COALESCE(MAX(sort_order), -1) + 1 AS next_sort
            FROM body_metric_photos
            WHERE body_metric_id = %s
            """,
            (metric_id,),
        ).fetchone()
        return int(row["next_sort"] if row else 0)


def update_body_metric(metric_id: int, patch: dict[str, Any]) -> dict[str, Any] | None:
    """Actualiza solo los campos presentes en `patch`. Campos desconocidos se ignoran."""
    allowed = [field for field in BODY_METRIC_INSERT_FIELDS if field in patch]
    with get_db() as conn:
        if allowed:
            assignments = ", ".join(f"{field} = %s" for field in allowed)
            row = conn.execute(
                f"UPDATE body_metrics SET {assignments} WHERE id = %s RETURNING *",
                tuple(patch[field] for field in allowed) + (metric_id,),
            ).fetchone()
            if not row:
                return None
            metric = dict(row)
        else:
            row = conn.execute(
                "SELECT * FROM body_metrics WHERE id = %s",
                (metric_id,),
            ).fetchone()
            if not row:
                return None
            metric = dict(row)
        _attach_body_metric_photos(conn, [metric])
        return metric


def delete_body_metric_photo(photo_id: int) -> dict[str, Any] | None:
    """Borra la fila y devuelve el registro previo (incluye object_key)."""
    with get_db() as conn:
        row = conn.execute(
            "DELETE FROM body_metric_photos WHERE id = %s RETURNING *",
            (photo_id,),
        ).fetchone()
        return dict(row) if row else None


def replace_body_metric_photo(
    photo_id: int,
    object_key: str,
    original_name: str | None,
    content_type: str,
    size_bytes: int,
) -> dict[str, Any] | None:
    """Sustituye metadata/object_key conservando id, metric y sort_order."""
    with get_db() as conn:
        row = conn.execute(
            """
            UPDATE body_metric_photos
            SET object_key = %s,
                original_name = %s,
                content_type = %s,
                size_bytes = %s
            WHERE id = %s
            RETURNING *
            """,
            (object_key, original_name, content_type, size_bytes, photo_id),
        ).fetchone()
        return _photo_payload(dict(row)) if row else None


def _user_profile_payload(row: dict[str, Any] | None) -> dict[str, Any]:
    has_photo = bool(row and row.get("photo_object_key"))
    return {
        "has_photo": has_photo,
        "photo_url": "/api/profile/photo" if has_photo else None,
        "photo_content_type": row.get("photo_content_type") if row else None,
        "photo_original_name": row.get("photo_original_name") if row else None,
        "photo_size_bytes": row.get("photo_size_bytes") if row else None,
        "photo_object_key": row.get("photo_object_key") if row else None,
        "updated_at": row.get("updated_at") if row else None,
    }


def get_user_profile() -> dict[str, Any]:
    with get_db() as conn:
        row = conn.execute("SELECT * FROM user_profile WHERE id = 1").fetchone()
        return _user_profile_payload(dict(row) if row else None)


def set_user_profile_photo(
    object_key: str,
    content_type: str,
    original_name: str | None,
    size_bytes: int,
) -> dict[str, Any]:
    with get_db() as conn:
        row = conn.execute(
            """
            INSERT INTO user_profile (
              id, photo_object_key, photo_content_type, photo_original_name,
              photo_size_bytes, updated_at
            )
            VALUES (1, %s, %s, %s, %s, %s)
            ON CONFLICT (id) DO UPDATE SET
              photo_object_key = EXCLUDED.photo_object_key,
              photo_content_type = EXCLUDED.photo_content_type,
              photo_original_name = EXCLUDED.photo_original_name,
              photo_size_bytes = EXCLUDED.photo_size_bytes,
              updated_at = EXCLUDED.updated_at
            RETURNING *
            """,
            (object_key, content_type, original_name, size_bytes, now_iso()),
        ).fetchone()
        return _user_profile_payload(dict(row))


def clear_user_profile_photo() -> dict[str, Any]:
    with get_db() as conn:
        row = conn.execute(
            """
            INSERT INTO user_profile (
              id, photo_object_key, photo_content_type, photo_original_name,
              photo_size_bytes, updated_at
            )
            VALUES (1, NULL, NULL, NULL, NULL, %s)
            ON CONFLICT (id) DO UPDATE SET
              photo_object_key = NULL,
              photo_content_type = NULL,
              photo_original_name = NULL,
              photo_size_bytes = NULL,
              updated_at = EXCLUDED.updated_at
            RETURNING *
            """,
            (now_iso(),),
        ).fetchone()
        return _user_profile_payload(dict(row))


def list_body_metrics(limit: int = 60) -> list[dict[str, Any]]:
    with get_db() as conn:
        rows = conn.execute(
            """
            SELECT * FROM body_metrics
            ORDER BY date DESC, measured_at DESC NULLS LAST, id DESC
            LIMIT %s
            """,
            (limit,),
        ).fetchall()
        metrics = [dict(r) for r in rows]
        _attach_body_metric_photos(conn, metrics)
        return metrics


def parse_renpho_csv(csv_text: str) -> list[dict[str, Any]]:
    reader = csv.DictReader(io.StringIO(csv_text.lstrip("\ufeff")))
    latest_by_date: dict[str, dict[str, Any]] = {}
    for raw_row in reader:
        if not raw_row.get("Fecha"):
            continue
        metric: dict[str, Any] = {}
        for source, target in RENPHO_FIELD_MAP.items():
            raw_value = raw_row.get(source)
            if target == "date":
                metric[target] = _parse_renpho_date(raw_value or "")
            elif target == "measured_at":
                metric[target] = _parse_renpho_time(raw_value)
            elif target in BODY_METRIC_TEXT_FIELDS:
                metric[target] = raw_value.strip() if raw_value else None
            else:
                metric[target] = _parse_float(raw_value)

        day = metric["date"]
        current = latest_by_date.get(day)
        if current is None or (metric.get("measured_at") or "") > (current.get("measured_at") or ""):
            latest_by_date[day] = metric
    return [latest_by_date[day] for day in sorted(latest_by_date)]


def import_renpho_csv(csv_text: str) -> dict[str, Any]:
    metrics = parse_renpho_csv(csv_text)
    imported: list[dict[str, Any]] = []
    with get_db() as conn:
        for metric in metrics:
            imported.append(_upsert_imported_body_metric_in_conn(conn, metric))
    return {
        "imported": len(imported),
        "dates": [m["date"] for m in imported],
        "latest": imported[-1] if imported else None,
    }


def add_run(
    day: str,
    distance_km: float,
    duration_min: float | None = None,
    pace_min_per_km: float | None = None,
    rpe: int | None = None,
    notes: str | None = None,
) -> dict[str, Any]:
    if pace_min_per_km is None and duration_min and distance_km:
        pace_min_per_km = duration_min / distance_km
    with get_db() as conn:
        row = conn.execute(
            """
            INSERT INTO runs (date, distance_km, duration_min, pace_min_per_km, rpe, notes, created_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            RETURNING *
            """,
            (day, distance_km, duration_min, pace_min_per_km, rpe, notes, now_iso()),
        ).fetchone()
        return dict(row)


def list_runs(limit: int = 60) -> list[dict[str, Any]]:
    with get_db() as conn:
        rows = conn.execute(
            "SELECT * FROM runs ORDER BY date DESC, id DESC LIMIT %s",
            (limit,),
        ).fetchall()
        return [dict(r) for r in rows]


# week_plan es el modelo antiguo, con un unico plan. Se conserva intacto: lo lee
# bootstrap_plans() una vez y despues solo lo escribe el espejo temporal de
# _mirror_active_to_week_plan(). Nadie mas debe tocarlo.


def save_week_plan(payload: dict[str, Any]) -> dict[str, Any]:
    with get_db() as conn:
        conn.execute(
            """
            INSERT INTO week_plan (id, payload, updated_at) VALUES (1, %s, %s)
            ON CONFLICT(id) DO UPDATE SET payload = excluded.payload, updated_at = excluded.updated_at
            """,
            (json.dumps(payload, ensure_ascii=False), now_iso()),
        )
        return payload


def load_week_plan() -> dict[str, Any] | None:
    with get_db() as conn:
        row = conn.execute("SELECT payload FROM week_plan WHERE id = 1").fetchone()
        if not row:
            return None
        return json.loads(row["payload"])


# --- Gimnasios virtuales -----------------------------------------------------

MAX_GYMS = 10
MAX_EQUIPMENT_PER_GYM = 100


def count_gyms() -> int:
    with get_db() as conn:
        return conn.execute("SELECT COUNT(*) AS n FROM gyms").fetchone()["n"]


def list_gyms() -> list[dict[str, Any]]:
    """Espacios con sus contadores.

    Los COUNT van como subconsultas correlacionadas y NO como dos LEFT JOIN:
    unir equipo y preferencias en la misma consulta multiplica filas y cada
    COUNT saldria inflado por el cardinal del otro. Las tablas son diminutas,
    asi que la subconsulta sale gratis y ademas se lee.
    """
    with get_db() as conn:
        rows = conn.execute(
            """
            SELECT g.*,
              (SELECT COUNT(*) FROM gym_equipment e WHERE e.gym_id = g.id)
                AS equipment_count,
              (SELECT COUNT(*) FROM gym_exercise_prefs p
                 WHERE p.gym_id = g.id AND p.state = 'favorito') AS favorite_count,
              (SELECT COUNT(*) FROM gym_exercise_prefs p
                 WHERE p.gym_id = g.id AND p.state = 'oculto') AS hidden_count
            FROM gyms g ORDER BY g.id
            """
        ).fetchall()
    return [dict(r) for r in rows]


def get_gym(gym_id: int) -> dict[str, Any] | None:
    with get_db() as conn:
        row = conn.execute("SELECT * FROM gyms WHERE id = %s", (gym_id,)).fetchone()
    return dict(row) if row else None


def gym_exists(gym_id: int) -> bool:
    with get_db() as conn:
        return conn.execute("SELECT 1 FROM gyms WHERE id = %s", (gym_id,)).fetchone() is not None


def gym_name_taken(name: str, *, exclude_id: int | None = None) -> bool:
    with get_db() as conn:
        # El cast explicito evita que Postgres se quede sin tipo con NULL.
        row = conn.execute(
            "SELECT id FROM gyms WHERE lower(name) = lower(%s) "
            "AND (%s::integer IS NULL OR id <> %s::integer)",
            (name.strip(), exclude_id, exclude_id),
        ).fetchone()
    return row is not None


def unique_gym_copy_name(base: str) -> str:
    from . import gyms as gyms_mod

    stem = base.strip()[: gyms_mod.MAX_GYM_NAME - 15]
    with get_db() as conn:
        taken = {r["n"] for r in conn.execute("SELECT lower(name) AS n FROM gyms").fetchall()}
    candidate, i = f"{stem} (copia)", 2
    while candidate.casefold() in taken:
        candidate, i = f"{stem} (copia {i})", i + 1
    return candidate


def create_gym(fields: dict[str, Any]) -> dict[str, Any]:
    from . import gyms as gyms_mod

    doc = gyms_mod.normalize_gym_fields(fields)
    ts = now_iso()
    with get_db() as conn:
        row = conn.execute(
            """
            INSERT INTO gyms (name, kind, icon, color, notes, created_at, updated_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s) RETURNING *
            """,
            (doc["name"], doc["kind"], doc["icon"], doc["color"], doc["notes"], ts, ts),
        ).fetchone()
    return dict(row)


def update_gym(gym_id: int, patch: dict[str, Any]) -> dict[str, Any] | None:
    """Parcial: lo que no venga en `patch` se conserva. El COALESCE deja pasar
    el borrado explicito de icon/color/notes mandando cadena vacia, que
    normalize_gym_fields convierte en None."""
    from . import gyms as gyms_mod

    current = get_gym(gym_id)
    if current is None:
        return None
    merged = {**current, **{k: v for k, v in patch.items() if v is not None}}
    doc = gyms_mod.normalize_gym_fields(merged)
    with get_db() as conn:
        row = conn.execute(
            """
            UPDATE gyms SET name = %s, kind = %s, icon = %s, color = %s,
                            notes = %s, updated_at = %s
            WHERE id = %s RETURNING *
            """,
            (doc["name"], doc["kind"], doc["icon"], doc["color"], doc["notes"], now_iso(), gym_id),
        ).fetchone()
    return dict(row) if row else None


def delete_gym(gym_id: int) -> bool:
    """El inventario y las preferencias se van por ON DELETE CASCADE. Los planes
    anclados NO se tocan: conservan el gym_id colgando y el borde HTTP los marca
    con `gym_missing` para que la UI ofrezca re-anclarlos."""
    with get_db() as conn:
        row = conn.execute("DELETE FROM gyms WHERE id = %s RETURNING id", (gym_id,)).fetchone()
    return row is not None


def duplicate_gym(gym_id: int, name: str | None = None) -> dict[str, Any] | None:
    source = get_gym(gym_id)
    if source is None:
        return None
    copy = create_gym(
        {**source, "name": name or unique_gym_copy_name(source["name"])}
    )
    ts = now_iso()
    with get_db() as conn:
        conn.execute(
            """
            INSERT INTO gym_equipment (gym_id, name, equipment_type, weight_kg, quantity, created_at)
            SELECT %s, name, equipment_type, weight_kg, quantity, %s
            FROM gym_equipment WHERE gym_id = %s
            """,
            (copy["id"], ts, gym_id),
        )
        conn.execute(
            """
            INSERT INTO gym_exercise_prefs (gym_id, exercise_id, state, created_at)
            SELECT %s, exercise_id, state, %s FROM gym_exercise_prefs WHERE gym_id = %s
            """,
            (copy["id"], ts, gym_id),
        )
    return copy


def resolve_gym_id(explicit: int | None = None) -> int | None:
    """El espacio que rige AHORA. Por orden:

      1. el que pida el cliente — es el cambio de espacio para una sesion
         suelta, que a proposito no se persiste en ningun sitio;
      2. el del plan activo;
      3. el primero que exista, para que nada reviente si el plan apunta a un
         espacio borrado o todavia no tiene ancla.

    Devuelve None solo si no hay ni un espacio, que tras bootstrap_gyms() no
    deberia pasar. No hay columna `is_default` a proposito: un flag puede
    desincronizarse del plan activo y crea la pregunta «cual gana» en cada
    endpoint.
    """
    if explicit is not None and gym_exists(explicit):
        return explicit
    active = get_active_plan()
    anchored = (active or {}).get("payload", {}).get("gym_id")
    if anchored is not None and gym_exists(anchored):
        return anchored
    with get_db() as conn:
        row = conn.execute("SELECT id FROM gyms ORDER BY id LIMIT 1").fetchone()
    return row["id"] if row else None


def list_gym_equipment(gym_id: int) -> list[dict[str, Any]]:
    with get_db() as conn:
        rows = conn.execute(
            "SELECT * FROM gym_equipment WHERE gym_id = %s ORDER BY equipment_type, name",
            (gym_id,),
        ).fetchall()
    return [dict(r) for r in rows]


def count_gym_equipment(gym_id: int) -> int:
    with get_db() as conn:
        return conn.execute(
            "SELECT COUNT(*) AS n FROM gym_equipment WHERE gym_id = %s", (gym_id,)
        ).fetchone()["n"]


def add_gym_equipment(
    gym_id: int,
    name: str,
    equipment_type: str,
    weight_kg: float | None = None,
    quantity: int = 1,
) -> dict[str, Any]:
    with get_db() as conn:
        row = conn.execute(
            """
            INSERT INTO gym_equipment (gym_id, name, equipment_type, weight_kg, quantity, created_at)
            VALUES (%s, %s, %s, %s, %s, %s) RETURNING *
            """,
            (gym_id, name, equipment_type, weight_kg, quantity, now_iso()),
        ).fetchone()
    return dict(row)


def delete_gym_equipment(gym_id: int, equipment_id: int) -> bool:
    with get_db() as conn:
        row = conn.execute(
            "DELETE FROM gym_equipment WHERE id = %s AND gym_id = %s RETURNING id",
            (equipment_id, gym_id),
        ).fetchone()
    return row is not None


def list_exercise_prefs(gym_id: int) -> dict[str, str]:
    with get_db() as conn:
        rows = conn.execute(
            "SELECT exercise_id, state FROM gym_exercise_prefs WHERE gym_id = %s",
            (gym_id,),
        ).fetchall()
    return {r["exercise_id"]: r["state"] for r in rows}


def set_exercise_pref(gym_id: int, exercise_id: str, state: str) -> str:
    """«disponible» NO se guarda: es la ausencia de fila, asi que volver a
    disponible es borrar la marca. Ese invariante lo sostiene esta funcion, no
    la base — un CHECK aqui no se podria ampliar nunca sin ALTER."""
    from . import gyms as gyms_mod

    state = gyms_mod.normalize_state(state)
    with get_db() as conn:
        if state == gyms_mod.STATE_AVAILABLE:
            conn.execute(
                "DELETE FROM gym_exercise_prefs WHERE gym_id = %s AND exercise_id = %s",
                (gym_id, exercise_id),
            )
        else:
            conn.execute(
                """
                INSERT INTO gym_exercise_prefs (gym_id, exercise_id, state, created_at)
                VALUES (%s, %s, %s, %s)
                ON CONFLICT (gym_id, exercise_id) DO UPDATE SET state = EXCLUDED.state
                """,
                (gym_id, exercise_id, state, now_iso()),
            )
    return state


def set_exercise_prefs(gym_id: int, marks: list[tuple[str, str]]) -> None:
    """Marcado masivo mixto en una sola transaccion: permite «estos 20 a
    favorito y estos 3 de vuelta a disponible» de golpe, que es como se usa el
    editor de la biblioteca."""
    from . import gyms as gyms_mod

    ts = now_iso()
    with get_db() as conn:
        for exercise_id, raw_state in marks:
            state = gyms_mod.normalize_state(raw_state)
            if state == gyms_mod.STATE_AVAILABLE:
                conn.execute(
                    "DELETE FROM gym_exercise_prefs WHERE gym_id = %s AND exercise_id = %s",
                    (gym_id, exercise_id),
                )
            else:
                conn.execute(
                    """
                    INSERT INTO gym_exercise_prefs (gym_id, exercise_id, state, created_at)
                    VALUES (%s, %s, %s, %s)
                    ON CONFLICT (gym_id, exercise_id) DO UPDATE SET state = EXCLUDED.state
                    """,
                    (gym_id, exercise_id, state, ts),
                )


def clear_exercise_prefs(gym_id: int) -> int:
    with get_db() as conn:
        cur = conn.execute("DELETE FROM gym_exercise_prefs WHERE gym_id = %s", (gym_id,))
        return cur.rowcount


def bootstrap_gyms() -> None:
    """Idempotente: corre en cada arranque y solo hace algo la primera vez.

    1. Si `gyms` esta vacia, crea el espacio «Casa» y copia dentro TODO el
       inventario global de `user_equipment` — que en produccion tiene el equipo
       real del usuario. Las filas viejas NO se borran ni se modifican:
       user_equipment queda como legado de solo lectura, igual que week_plan.
    2. Si user_equipment tambien estaba vacia (base recien creada), siembra
       DEFAULT_EQUIPMENT directamente dentro del espacio.
    3. No toca los planes: un plan sin `gym_id` lo resuelve resolve_gym_id() al
       primer espacio, asi que no hace falta reescribir ningun payload guardado.

    Todo va en UNA sola transaccion, a diferencia de bootstrap_plans(): aqui la
    guarda y la escritura no se pueden separar. Una caida entre medias dejaria
    un espacio vacio que la guarda del COUNT ya daria por sembrado, y el equipo
    del usuario no se copiaria jamas.
    """
    from . import gyms as gyms_mod

    with get_db() as conn:
        if conn.execute("SELECT COUNT(*) AS n FROM gyms").fetchone()["n"]:
            return

        ts = now_iso()
        legacy = conn.execute(
            """
            SELECT name, equipment_type, weight_kg,
                   COALESCE(quantity, 1) AS quantity, created_at
            FROM user_equipment ORDER BY id
            """
        ).fetchall()

        # ON CONFLICT + RETURNING: si dos workers arrancan a la vez, el segundo
        # choca contra gyms_name_unique, no devuelve fila y se va sin sembrar.
        # El COUNT de arriba no es un cerrojo; el indice unico si.
        gym = conn.execute(
            """
            INSERT INTO gyms (name, kind, icon, created_at, updated_at)
            VALUES (%s, %s, %s, %s, %s)
            ON CONFLICT (lower(name)) DO NOTHING
            RETURNING id
            """,
            (
                gyms_mod.DEFAULT_GYM_NAME,
                gyms_mod.DEFAULT_KIND,
                gyms_mod.DEFAULT_GYM_ICON,
                # created_at hereda la fecha del equipo mas antiguo: el espacio
                # no nacio el dia del despliegue. Las fechas son ISO en TEXT, asi
                # que el orden lexicografico es el cronologico.
                min((r["created_at"] for r in legacy), default=ts),
                ts,
            ),
        ).fetchone()
        if gym is None:
            return

        rows: list[dict[str, Any]] = [dict(r) for r in legacy] or [
            {"name": n, "equipment_type": t, "weight_kg": w, "quantity": q, "created_at": ts}
            for n, t, w, q in DEFAULT_EQUIPMENT
        ]
        for r in rows:
            conn.execute(
                """
                INSERT INTO gym_equipment
                  (gym_id, name, equipment_type, weight_kg, quantity, created_at)
                VALUES (%s, %s, %s, %s, %s, %s)
                """,
                (
                    gym["id"], r["name"], r["equipment_type"],
                    r["weight_kg"], r["quantity"], r["created_at"],
                ),
            )


# --- Planes -----------------------------------------------------------------

MAX_PLANS = 20


def _plan_row(row: Any) -> dict[str, Any]:
    """Toda lectura de un plan pasa por aqui: el payload sale siempre
    normalizado a v2, venga de una fila v1 o de una v2."""
    from . import plans as plans_mod

    out = dict(row)
    out["payload"] = plans_mod.normalize_plan_payload(json.loads(out["payload"]))
    out["is_active"] = bool(out["is_active"])
    return out


def count_plans() -> int:
    with get_db() as conn:
        return conn.execute("SELECT COUNT(*) AS n FROM plans").fetchone()["n"]


def list_plans() -> list[dict[str, Any]]:
    with get_db() as conn:
        rows = conn.execute("SELECT * FROM plans ORDER BY id").fetchall()
    return [_plan_row(r) for r in rows]


def get_plan(plan_id: int) -> dict[str, Any] | None:
    with get_db() as conn:
        row = conn.execute("SELECT * FROM plans WHERE id = %s", (plan_id,)).fetchone()
    return _plan_row(row) if row else None


def get_active_plan() -> dict[str, Any] | None:
    with get_db() as conn:
        row = conn.execute("SELECT * FROM plans WHERE is_active = 1").fetchone()
    return _plan_row(row) if row else None


def load_active_plan() -> dict[str, Any] | None:
    """Solo el payload del plan activo. Sustituye a load_week_plan()."""
    row = get_active_plan()
    return row["payload"] if row else None


def name_taken(name: str, *, exclude_id: int | None = None) -> bool:
    with get_db() as conn:
        # El cast explicito evita que Postgres se quede sin tipo cuando
        # exclude_id llega a NULL.
        row = conn.execute(
            "SELECT id FROM plans WHERE lower(name) = lower(%s) "
            "AND (%s::integer IS NULL OR id <> %s::integer)",
            (name.strip(), exclude_id, exclude_id),
        ).fetchone()
    return row is not None


def unique_copy_name(base: str) -> str:
    """«Piernas» -> «Piernas (copia)» -> «Piernas (copia 2)»... El indice unico
    sobre lower(name) es la verdad; esto solo evita el 409 obvio."""
    from . import plans as plans_mod

    stem = base.strip()[: plans_mod.MAX_NAME - 15]  # deja hueco para el sufijo
    with get_db() as conn:
        taken = {r["n"] for r in conn.execute("SELECT lower(name) AS n FROM plans").fetchall()}
    candidate, i = f"{stem} (copia)", 2
    while candidate.casefold() in taken:
        candidate, i = f"{stem} (copia {i})", i + 1
    return candidate


def _activate_in_conn(conn: psycopg.Connection, plan_id: int) -> bool:
    """El orden importa: primero se apaga el activo y despues se enciende el
    nuevo, porque el indice parcial plans_single_active no admite dos a la vez.
    Las dos sentencias van en la misma transaccion.

    No toca updated_at: activar no es editar, y ese orden se usa para elegir
    sucesor al borrar.
    """
    conn.execute("UPDATE plans SET is_active = 0 WHERE is_active = 1")
    row = conn.execute(
        "UPDATE plans SET is_active = 1 WHERE id = %s RETURNING id", (plan_id,)
    ).fetchone()
    return row is not None


def create_plan(name: str, payload: dict[str, Any], *, activate: bool = False) -> dict[str, Any]:
    from . import plans as plans_mod

    doc = plans_mod.normalize_plan_payload({**payload, "name": name})
    ts = now_iso()
    with get_db() as conn:
        row = conn.execute(
            """
            INSERT INTO plans (name, payload, is_active, created_at, updated_at)
            VALUES (%s, %s, 0, %s, %s) RETURNING *
            """,
            (doc["name"], json.dumps(doc, ensure_ascii=False), ts, ts),
        ).fetchone()
        if activate:
            _activate_in_conn(conn, row["id"])
            row = conn.execute("SELECT * FROM plans WHERE id = %s", (row["id"],)).fetchone()
    if activate:
        _mirror_active_to_week_plan()
    return _plan_row(row)


def update_plan(
    plan_id: int,
    *,
    name: str | None = None,
    payload: dict[str, Any] | None = None,
) -> dict[str, Any] | None:
    """Fusiona sobre el payload actual, para que un cliente que solo manda
    `days` no borre los objetivos del plan."""
    from . import plans as plans_mod

    current = get_plan(plan_id)
    if current is None:
        return None
    base = payload if payload is not None else current["payload"]
    doc = plans_mod.normalize_plan_payload(
        {**base, "name": name or base.get("name") or current["name"]}
    )
    with get_db() as conn:
        row = conn.execute(
            "UPDATE plans SET name = %s, payload = %s, updated_at = %s "
            "WHERE id = %s RETURNING *",
            (doc["name"], json.dumps(doc, ensure_ascii=False), now_iso(), plan_id),
        ).fetchone()
    if row is None:
        return None
    if row["is_active"]:
        _mirror_active_to_week_plan()
    return _plan_row(row)


def duplicate_plan(plan_id: int, name: str | None = None) -> dict[str, Any] | None:
    source = get_plan(plan_id)
    if source is None:
        return None
    return create_plan(name or unique_copy_name(source["payload"]["name"]), source["payload"])


def activate_plan(plan_id: int) -> bool:
    with get_db() as conn:
        ok = _activate_in_conn(conn, plan_id)
    if ok:
        _mirror_active_to_week_plan()
    return ok


def delete_plan(plan_id: int) -> dict[str, Any]:
    """El caller ya comprobo que no es el ultimo plan. Si el borrado era el
    activo se activa el siguiente (el editado mas recientemente), para que nunca
    queden cero activos."""
    with get_db() as conn:
        row = conn.execute(
            "DELETE FROM plans WHERE id = %s RETURNING is_active", (plan_id,)
        ).fetchone()
        if row is None:
            return {"deleted": None, "active_id": None}
        if row["is_active"]:
            nxt = conn.execute(
                "SELECT id FROM plans ORDER BY updated_at DESC, id DESC LIMIT 1"
            ).fetchone()
            if nxt:
                _activate_in_conn(conn, nxt["id"])
        active = conn.execute("SELECT id FROM plans WHERE is_active = 1").fetchone()
    _mirror_active_to_week_plan()
    return {"deleted": plan_id, "active_id": active["id"] if active else None}


def _mirror_active_to_week_plan() -> None:
    """Espeja el plan activo en la tabla vieja week_plan, en formato v1. Red de
    seguridad para poder revertir el despliegue durante una release sin que el
    codigo anterior lea una rutina congelada en el momento del backfill.

    TODO: borrar esta funcion y sus llamadas en la release siguiente.
    """
    from . import plans as plans_mod

    payload = load_active_plan()
    if payload is not None:
        save_week_plan(plans_mod.plan_v1_projection(payload))


def bootstrap_plans() -> None:
    """Idempotente: corre en cada arranque y solo hace algo la primera vez.

    1. Si `plans` esta vacia, copia el singleton week_plan -que en produccion
       tiene la rutina real del usuario- como primer plan y lo deja activo. La
       fila de week_plan NO se borra ni se modifica.
    2. Si no habia week_plan (base nueva), siembra el plan por defecto del
       catalogo.
    3. Garantiza que siempre haya exactamente un plan activo, tambien si alguien
       apago el flag a mano.
    """
    from . import catalog
    from . import plans as plans_mod

    if count_plans() == 0:
        with get_db() as conn:
            legacy = conn.execute(
                "SELECT payload, updated_at FROM week_plan WHERE id = 1"
            ).fetchone()
            source = json.loads(legacy["payload"]) if legacy else catalog.default_week()
            doc = plans_mod.normalize_plan_payload(source)
            ts = now_iso()
            conn.execute(
                """
                INSERT INTO plans (name, payload, is_active, created_at, updated_at)
                VALUES (%s, %s, 1, %s, %s)
                ON CONFLICT (lower(name)) DO NOTHING
                """,
                (
                    doc["name"],
                    json.dumps(doc, ensure_ascii=False),
                    # created_at hereda la fecha de la fila vieja: el plan no se
                    # creo el dia del despliegue.
                    legacy["updated_at"] if legacy else ts,
                    ts,
                ),
            )

    with get_db() as conn:
        active = conn.execute(
            "SELECT COUNT(*) AS n FROM plans WHERE is_active = 1"
        ).fetchone()["n"]
        if not active:
            first = conn.execute("SELECT id FROM plans ORDER BY id LIMIT 1").fetchone()
            if first:
                _activate_in_conn(conn, first["id"])


def save_coach_note(week_start: str, advice: str, source: str, prompt_summary: str = "") -> dict[str, Any]:
    with get_db() as conn:
        row = conn.execute(
            """
            INSERT INTO coach_notes (created_at, week_start, prompt_summary, advice, source)
            VALUES (%s, %s, %s, %s, %s)
            RETURNING *
            """,
            (now_iso(), week_start, prompt_summary, advice, source),
        ).fetchone()
        return dict(row)


def latest_coach_note() -> dict[str, Any] | None:
    with get_db() as conn:
        row = conn.execute("SELECT * FROM coach_notes ORDER BY id DESC LIMIT 1").fetchone()
        return dict(row) if row else None


def week_bounds(ref: date | None = None) -> tuple[str, str]:
    d = ref or date.today()
    start = d - timedelta(days=d.weekday())
    end = start + timedelta(days=6)
    return start.isoformat(), end.isoformat()


def add_user_equipment(name: str, equipment_type: str, weight_kg: float | None = None, quantity: int = 1) -> dict[str, Any]:
    with get_db() as conn:
        row = conn.execute(
            """
            INSERT INTO user_equipment (name, equipment_type, weight_kg, quantity, created_at)
            VALUES (%s, %s, %s, %s, %s)
            RETURNING *
            """,
            (name, equipment_type, weight_kg, quantity, now_iso()),
        ).fetchone()
        return dict(row)


def list_user_equipment() -> list[dict[str, Any]]:
    with get_db() as conn:
        rows = conn.execute("SELECT * FROM user_equipment ORDER BY equipment_type, name").fetchall()
        return [dict(r) for r in rows]


def delete_user_equipment(equipment_id: int) -> None:
    with get_db() as conn:
        conn.execute("DELETE FROM user_equipment WHERE id = %s", (equipment_id,))


def list_dumbbell_weights(gym_id: int | None = None) -> list[float]:
    """Mancuernas distintas que hay en un espacio, de menor a mayor.

    Sin argumento resuelve sola el espacio en efecto. Devuelve lista vacia si no
    hay ningun espacio o si el espacio no tiene mancuernas — un parque es un
    caso legitimo, no un error.
    """
    gid = resolve_gym_id(gym_id)
    if gid is None:
        return []
    with get_db() as conn:
        rows = conn.execute(
            """
            SELECT DISTINCT weight_kg FROM gym_equipment
            WHERE gym_id = %s AND equipment_type = 'dumbbell' AND weight_kg IS NOT NULL
            ORDER BY weight_kg
            """,
            (gid,),
        ).fetchall()
        return [float(r["weight_kg"]) for r in rows]


DEFAULT_EQUIPMENT = [
    ("Mancuerna 7.5 kg", "dumbbell", 7.5, 2),
    ("Mancuerna 12.5 kg", "dumbbell", 12.5, 2),
    ("Mancuerna 20 kg", "dumbbell", 20.0, 2),
    ("Banca inclinable", "bench", None, 1),
    ("Barra de dominadas", "pull_up_bar", None, 1),
    ("Juego de ligas de colores", "band", None, 1),
    ("Rueda abdominal", "wheel", None, 1),
]


def seed_default_equipment() -> None:
    """Populate the equipment inventory on first run so the app works out of the box."""
    with get_db() as conn:
        count = conn.execute("SELECT COUNT(*) AS n FROM user_equipment").fetchone()["n"]
        if count:
            return
        for name, eq_type, weight, qty in DEFAULT_EQUIPMENT:
            conn.execute(
                """
                INSERT INTO user_equipment (name, equipment_type, weight_kg, quantity, created_at)
                VALUES (%s, %s, %s, %s, %s)
                """,
                (name, eq_type, weight, qty, now_iso()),
            )


def get_volume_by_muscle(start: str, end: str) -> dict[str, float]:
    """Get total volume (reps × weight) per muscle group for the period."""
    from . import catalog
    emap = catalog.exercise_map()

    with get_db() as conn:
        rows = conn.execute(
            """
            SELECT ss.exercise_id,
              CAST(SUM(ss.reps * COALESCE(ss.weight_kg, 0)) AS DOUBLE PRECISION) as volume
            FROM session_sets ss
            JOIN sessions s ON s.id = ss.session_id
            WHERE s.date BETWEEN %s AND %s AND ss.done = 1 AND s.completed = 1
            GROUP BY ss.exercise_id
            """,
            (start, end),
        ).fetchall()

    muscle_volumes: dict[str, float] = {}
    for row in rows:
        ex = emap.get(row["exercise_id"])
        if ex:
            target = ex.get("target", "other")
            volume = float(row["volume"] or 0)
            muscle_volumes[target] = muscle_volumes.get(target, 0) + volume

    return muscle_volumes


def get_exercise_frequency(start: str, end: str, limit: int = 10) -> dict[str, int]:
    """Get how many times each exercise was performed."""
    with get_db() as conn:
        rows = conn.execute(
            """
            SELECT ss.exercise_id, COUNT(DISTINCT s.date) as frequency
            FROM session_sets ss
            JOIN sessions s ON s.id = ss.session_id
            WHERE s.date BETWEEN %s AND %s AND ss.done = 1 AND s.completed = 1
            GROUP BY ss.exercise_id
            ORDER BY frequency DESC
            LIMIT %s
            """,
            (start, end, limit),
        ).fetchall()
    return {row["exercise_id"]: row["frequency"] for row in rows}


def get_exercise_max_weight(exercise_id: str) -> float | None:
    """Get the maximum weight ever lifted for an exercise."""
    with get_db() as conn:
        row = conn.execute(
            """
            SELECT MAX(ss.weight_kg) as max_weight
            FROM session_sets ss
            JOIN sessions s ON s.id = ss.session_id
            WHERE ss.exercise_id = %s AND ss.weight_kg > 0
              AND ss.done = 1 AND s.completed = 1
            """,
            (exercise_id,),
        ).fetchone()
    return float(row["max_weight"]) if row and row["max_weight"] else None


def get_exercise_history(exercise_id: str, limit: int = 20) -> list[dict[str, Any]]:
    """Get weight history for an exercise (for PR progression)."""
    with get_db() as conn:
        rows = conn.execute(
            """
            SELECT s.date, MAX(ss.weight_kg) as max_weight, MAX(ss.reps) as max_reps
            FROM session_sets ss
            JOIN sessions s ON s.id = ss.session_id
            WHERE ss.exercise_id = %s AND ss.weight_kg > 0
              AND ss.done = 1 AND s.completed = 1
            GROUP BY s.date
            ORDER BY s.date DESC
            LIMIT %s
            """,
            (exercise_id, limit),
        ).fetchall()
    return [dict(r) for r in reversed(rows)]


TARGET_SESSIONS_PER_14D = 2  # how many hits/2wk a muscle "should" get for 100% coverage


def get_muscle_stats(start: str, end: str) -> dict[str, dict[str, Any]]:
    """Per-muscle sessions/volume/last-trained-date for [start, end], zero-filled
    for every muscle target in the catalog (not just ones with data) so
    never-trained groups show up correctly."""
    from . import catalog

    emap = catalog.exercise_map()
    all_targets = {e.get("target", "other") for e in emap.values()}
    stats: dict[str, dict[str, Any]] = {
        m: {"volume_kg": 0.0, "dates": set(), "last_date": None} for m in all_targets
    }

    with get_db() as conn:
        rows = conn.execute(
            """
            SELECT ss.exercise_id, s.date,
              CAST(SUM(ss.reps * COALESCE(ss.weight_kg, 0)) AS DOUBLE PRECISION) as volume
            FROM session_sets ss
            JOIN sessions s ON s.id = ss.session_id
            WHERE s.date BETWEEN %s AND %s AND ss.done = 1 AND s.completed = 1
            GROUP BY ss.exercise_id, s.date
            """,
            (start, end),
        ).fetchall()

    for row in rows:
        ex = emap.get(row["exercise_id"])
        if not ex:
            continue
        m = ex.get("target", "other")
        stats[m]["volume_kg"] += float(row["volume"] or 0)
        stats[m]["dates"].add(row["date"])
        if stats[m]["last_date"] is None or row["date"] > stats[m]["last_date"]:
            stats[m]["last_date"] = row["date"]

    return {
        m: {"volume_kg": s["volume_kg"], "sessions": len(s["dates"]), "last_date": s["last_date"]}
        for m, s in stats.items()
    }


def coverage_pct(sessions: int, window_days: int) -> int:
    target = TARGET_SESSIONS_PER_14D * (window_days / 14)
    return min(100, round(100 * sessions / target)) if target > 0 else 0


def count_prs_this_month(month_start: str, month_end: str) -> int:
    """A PR = an exercise's max weight in the window beats (or is the first
    time reaching) its all-time max weight from strictly before the window."""
    with get_db() as conn:
        # Postgres no admite alias del SELECT dentro de HAVING (a diferencia de
        # sqlite), asi que la condicion repite la expresion agregada completa.
        rows = conn.execute(
            """
            SELECT ss.exercise_id,
              MAX(CASE WHEN s.date >= %s AND s.date <= %s THEN ss.weight_kg END) as month_max,
              MAX(CASE WHEN s.date < %s THEN ss.weight_kg END) as prior_max
            FROM session_sets ss
            JOIN sessions s ON s.id = ss.session_id
            WHERE ss.weight_kg > 0 AND ss.done = 1 AND s.completed = 1
            GROUP BY ss.exercise_id
            HAVING MAX(CASE WHEN s.date >= %s AND s.date <= %s THEN ss.weight_kg END) IS NOT NULL
            """,
            (month_start, month_end, month_start, month_start, month_end),
        ).fetchall()
    return sum(1 for r in rows if r["prior_max"] is None or r["month_max"] > r["prior_max"])


def get_strength_window_summary(start: str, end: str) -> dict[str, Any]:
    """Completed strength sessions and tonnage inside a dashboard window."""
    with get_db() as conn:
        row = conn.execute(
            """
            SELECT COUNT(DISTINCT s.date) AS sessions,
              CAST(SUM(ss.reps * COALESCE(ss.weight_kg, 0)) AS DOUBLE PRECISION) AS volume_kg
            FROM session_sets ss
            JOIN sessions s ON s.id = ss.session_id
            WHERE s.date BETWEEN %s AND %s AND ss.done = 1 AND s.completed = 1
            """,
            (start, end),
        ).fetchone()
    return {
        "sessions": int(row["sessions"] or 0),
        "volume_kg": float(row["volume_kg"] or 0),
    }


def get_strength_weekly_volume(start: str, end: str) -> list[dict[str, Any]]:
    """Completed strength tonnage grouped by ISO week."""
    with get_db() as conn:
        rows = conn.execute(
            """
            SELECT DATE_TRUNC('week', s.date::date)::date AS week_start,
              COUNT(DISTINCT s.date) AS sessions,
              CAST(SUM(ss.reps * COALESCE(ss.weight_kg, 0)) AS DOUBLE PRECISION) AS volume_kg
            FROM session_sets ss
            JOIN sessions s ON s.id = ss.session_id
            WHERE s.date BETWEEN %s AND %s AND ss.done = 1 AND s.completed = 1
            GROUP BY DATE_TRUNC('week', s.date::date)::date
            ORDER BY week_start
            """,
            (start, end),
        ).fetchall()
    return [
        {
            "week_start": row["week_start"].isoformat(),
            "sessions": int(row["sessions"] or 0),
            "volume_kg": round(float(row["volume_kg"] or 0), 1),
        }
        for row in rows
    ]


def get_strength_exercises(start: str, end: str) -> list[dict[str, Any]]:
    """Exercises with completed history, enriched with metrics for the window."""
    with get_db() as conn:
        rows = conn.execute(
            """
            SELECT ss.exercise_id,
              COUNT(DISTINCT s.date) FILTER (WHERE s.date BETWEEN %s AND %s) AS sessions,
              CAST(SUM(ss.reps * COALESCE(ss.weight_kg, 0))
                FILTER (WHERE s.date BETWEEN %s AND %s) AS DOUBLE PRECISION) AS volume_kg,
              MAX(ss.weight_kg) FILTER (WHERE s.date BETWEEN %s AND %s) AS window_max_weight,
              MAX(ss.weight_kg) AS all_time_max_weight,
              MAX(s.date) AS last_date
            FROM session_sets ss
            JOIN sessions s ON s.id = ss.session_id
            WHERE ss.done = 1 AND s.completed = 1
            GROUP BY ss.exercise_id
            ORDER BY sessions DESC, last_date DESC
            """,
            (start, end, start, end, start, end),
        ).fetchall()
    return [
        {
            "exercise_id": row["exercise_id"],
            "sessions": int(row["sessions"] or 0),
            "volume_kg": round(float(row["volume_kg"] or 0), 1),
            "window_max_weight": (
                float(row["window_max_weight"]) if row["window_max_weight"] is not None else None
            ),
            "all_time_max_weight": (
                float(row["all_time_max_weight"]) if row["all_time_max_weight"] is not None else None
            ),
            "last_date": row["last_date"],
        }
        for row in rows
    ]


def get_strength_prs(start: str, end: str, limit: int = 8) -> list[dict[str, Any]]:
    """Best all-time weight records reached inside the selected window."""
    with get_db() as conn:
        rows = conn.execute(
            """
            WITH window_max AS (
              SELECT ss.exercise_id, MAX(ss.weight_kg) AS max_weight
              FROM session_sets ss
              JOIN sessions s ON s.id = ss.session_id
              WHERE s.date BETWEEN %s AND %s AND ss.weight_kg > 0
                AND ss.done = 1 AND s.completed = 1
              GROUP BY ss.exercise_id
            ),
            prior_max AS (
              SELECT ss.exercise_id, MAX(ss.weight_kg) AS max_weight
              FROM session_sets ss
              JOIN sessions s ON s.id = ss.session_id
              WHERE s.date < %s AND ss.weight_kg > 0
                AND ss.done = 1 AND s.completed = 1
              GROUP BY ss.exercise_id
            ),
            winners AS (
              SELECT DISTINCT ON (ss.exercise_id)
                ss.exercise_id, s.date, ss.weight_kg, ss.reps
              FROM session_sets ss
              JOIN sessions s ON s.id = ss.session_id
              JOIN window_max w
                ON w.exercise_id = ss.exercise_id AND w.max_weight = ss.weight_kg
              WHERE s.date BETWEEN %s AND %s
                AND ss.done = 1 AND s.completed = 1
              ORDER BY ss.exercise_id, s.date DESC, ss.reps DESC NULLS LAST
            )
            SELECT w.exercise_id, w.date, w.weight_kg, w.reps,
              p.max_weight AS previous_weight
            FROM winners w
            LEFT JOIN prior_max p ON p.exercise_id = w.exercise_id
            WHERE p.max_weight IS NULL OR w.weight_kg > p.max_weight
            ORDER BY w.date DESC, w.weight_kg DESC
            LIMIT %s
            """,
            (start, end, start, start, end, limit),
        ).fetchall()
    return [
        {
            "exercise_id": row["exercise_id"],
            "date": row["date"],
            "weight_kg": float(row["weight_kg"]),
            "reps": int(row["reps"]) if row["reps"] is not None else None,
            "previous_weight_kg": (
                float(row["previous_weight"]) if row["previous_weight"] is not None else None
            ),
        }
        for row in rows
    ]


def compute_weekly_load(start: str, end: str) -> dict[str, Any]:
    sessions = list_sessions(start, end)
    with get_db() as conn:
        runs = conn.execute(
            "SELECT * FROM runs WHERE date BETWEEN %s AND %s ORDER BY date",
            (start, end),
        ).fetchall()
        weights = conn.execute(
            "SELECT * FROM body_metrics WHERE date BETWEEN %s AND %s ORDER BY date",
            (start, end),
        ).fetchall()

    completed = [s for s in sessions if s["completed"]]
    volume = sum(float(s["volume_kg"] or 0) for s in completed)
    set_count = sum(int(s["set_count"] or 0) for s in completed)
    rpes = [s["session_rpe"] for s in completed if s.get("session_rpe")]
    set_rpes = [s["avg_set_rpe"] for s in completed if s.get("avg_set_rpe")]
    run_km = sum(float(r["distance_km"] or 0) for r in runs)
    avg_session_rpe = sum(rpes) / len(rpes) if rpes else None
    avg_set_rpe = sum(set_rpes) / len(set_rpes) if set_rpes else None

    # Simple strain index: volume tonnage + run load + RPE factor
    rpe_factor = (avg_session_rpe or avg_set_rpe or 5) / 10
    strain = round((volume / 1000) + (run_km * 2) + (len(completed) * 3 * rpe_factor), 1)

    return {
        "week_start": start,
        "week_end": end,
        "training_days": len(completed),
        "planned_or_logged_days": len(sessions),
        "total_volume_kg": round(volume, 1),
        "total_sets": set_count,
        "avg_session_rpe": round(avg_session_rpe, 1) if avg_session_rpe else None,
        "avg_set_rpe": round(avg_set_rpe, 1) if avg_set_rpe else None,
        "run_distance_km": round(run_km, 2),
        "run_count": len(runs),
        "strain_index": strain,
        "body_weights": [dict(w) for w in weights],
        "sessions": sessions,
        "runs": [dict(r) for r in runs],
    }


def _monday(d: date) -> date:
    return d - timedelta(days=d.weekday())


def _metric_delta(latest: dict[str, Any] | None, oldest: dict[str, Any] | None) -> dict[str, float | None]:
    if not latest or not oldest:
        return {"weight_kg": None, "body_fat_pct": None, "muscle_pct": None}
    out: dict[str, float | None] = {}
    for field in ("weight_kg", "body_fat_pct", "muscle_pct"):
        a, b = latest.get(field), oldest.get(field)
        out[field] = round(float(a) - float(b), 2) if a is not None and b is not None else None
    return out


def profile_summary(window_days: int = 28) -> dict[str, Any]:
    window_days = max(7, min(window_days, 180))
    end_d = date.today()
    start_d = end_d - timedelta(days=window_days - 1)
    start, end = start_d.isoformat(), end_d.isoformat()
    sessions = list_sessions(start, end)
    sessions_by_date = {date.fromisoformat(s["date"]): s for s in sessions}
    completed_dates = {d for d, s in sessions_by_date.items() if s["completed"]}
    plan = load_active_plan() or {"days": []}
    planned_weekdays = {int(d["weekday"]) for d in plan.get("days", []) if d.get("items")}

    weeks: dict[str, dict[str, Any]] = {}
    calendar: list[dict[str, Any]] = []
    planned_count = 0
    completed_on_plan = 0
    total_volume = 0.0
    cursor = start_d
    calendar_end_d = _monday(end_d) + timedelta(days=6)
    while cursor <= calendar_end_d:
        week_key = _monday(cursor).isoformat()
        planned = cursor.weekday() in planned_weekdays
        sess = sessions_by_date.get(cursor)
        completed = bool(sess and sess["completed"])
        volume = float(sess.get("volume_kg") or 0) if completed and sess else 0.0
        if cursor > end_d:
            status = "future"
        elif completed and planned:
            status = "completed"
        elif completed:
            status = "bonus"
        elif planned:
            status = "missed"
        else:
            status = "rest"

        calendar.append(
            {
                "date": cursor.isoformat(),
                "weekday": cursor.weekday(),
                "planned": planned,
                "completed": completed,
                "status": status,
                "volume_kg": round(volume, 1),
                "focus": sess.get("focus") if sess else None,
            }
        )

        if cursor <= end_d:
            weeks.setdefault(
                week_key,
                {
                    "week_start": week_key,
                    "planned_days": 0,
                    "completed_days": 0,
                    "missed_dates": [],
                    "volume_kg": 0.0,
                },
            )
            if planned:
                planned_count += 1
                weeks[week_key]["planned_days"] += 1
                if completed:
                    completed_on_plan += 1
                else:
                    weeks[week_key]["missed_dates"].append(cursor.isoformat())
            if completed:
                weeks[week_key]["completed_days"] += 1
                weeks[week_key]["volume_kg"] += volume
                total_volume += volume
        cursor += timedelta(days=1)

    streak = 0
    cursor = end_d
    while cursor in completed_dates:
        streak += 1
        cursor -= timedelta(days=1)

    with get_db() as conn:
        body_rows = conn.execute(
            """
            SELECT * FROM body_metrics
            WHERE date BETWEEN %s AND %s
            ORDER BY date ASC, measured_at ASC NULLS LAST, id ASC
            """,
            (start, end),
        ).fetchall()

    body = [dict(r) for r in body_rows]
    with get_db() as conn:
        _attach_body_metric_photos(conn, body)
    oldest = body[0] if body else None
    latest = body[-1] if body else None
    adherence = round(100 * completed_on_plan / planned_count) if planned_count else 0
    current_week = _monday(end_d).isoformat()
    previous_week = (_monday(end_d) - timedelta(days=7)).isoformat()

    def week_detail(week_start: str) -> dict[str, Any]:
        week = weeks.get(
            week_start,
            {
                "week_start": week_start,
                "planned_days": 0,
                "completed_days": 0,
                "missed_dates": [],
                "volume_kg": 0.0,
            },
        )
        return {
            "week_start": week_start,
            "planned_days": week["planned_days"],
            "completed_days": week["completed_days"],
            "missed_dates": week["missed_dates"],
            "volume_kg": round(float(week["volume_kg"]), 1),
        }

    return {
        "window_days": window_days,
        "start": start,
        "end": end,
        "calendar": calendar,
        "week_compare": {
            "current": week_detail(current_week),
            "previous": week_detail(previous_week),
        },
        "consistency": {
            "planned_days": planned_count,
            "completed_days": len(completed_dates),
            "completed_planned_days": completed_on_plan,
            "adherence_pct": min(100, adherence),
            "current_streak_days": streak,
        },
        "volume": {
            "total_volume_kg": round(total_volume, 1),
            "weeks": [
                {
                    "week_start": week["week_start"],
                    "planned_days": week["planned_days"],
                    "completed_days": week["completed_days"],
                    "volume_kg": round(float(week["volume_kg"]), 1),
                }
                for week in sorted(weeks.values(), key=lambda w: w["week_start"])
            ],
        },
        "composition": {
            "latest": latest,
            "oldest": oldest,
            "delta": _metric_delta(latest, oldest),
        },
    }
